name: CI/CD
on:
  push:
    tags:
      - 'R*'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false

      - name: Set Node version 📦
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true

      - name: Install and Build 🔧
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          CALENDAR_ID: ${{ secrets.CALENDAR_ID }}
          EVENT_ID: ${{ secrets.EVENT_ID }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        run: |
          yarn
          yarn build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist
