name: UI checks
run-name: ${{ github.actor }} is linting and formatting
on:
  workflow_call:
  pull_request:
    branches:
      - 'main'
jobs:
  lint-format:
    name: Lint 🔎, Format ✅
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: './.nvmrc'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: run format
        run: pnpm format

      - name: run linter
        run: pnpm lint
